"""
TinyML AKF Training Pipeline (3-feature baseline) — rev2
=========================================================
Thesis: Edge AI 기반 적응형 칼만 필터의 임베디드 실시간 적용 연구

Revision notes (rev2):
  - Label transformed to log1p(R) for heavy-tailed distribution stability
  - R_label clamped to [1.0, 10000.0] matching CM-AKF definition (Mehra 1970)
  - Output activation changed softplus -> linear (log-space)
  - Training epochs reduced; early stopping sufficient in log-space

Pipeline:
  1. Load synthetic data (E1~E5) generated by synth_data_generator.py
  2. Extract F1 (Residual), F2 (Residual Variance), F3 (Residual Mean)
  3. Use CM-AKF R_label clamped, transformed to log1p space
  4. Train FCN: 3 -> Dense(16, ReLU) -> Dense(8, ReLU) -> Dense(1, linear)
  5. INT8 quantization via TFLite Converter
  6. Verify float32 vs int8 R estimation within 10%
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from pathlib import Path
import glob

# ---------- Reproducibility ----------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ---------- Config ----------
DATA_DIR = Path("data")
WINDOW_SIZE = 20
FEATURE_NAMES = ["F1_residual", "F2_residual_var", "F3_residual_mean"]
N_FEATURES = len(FEATURE_NAMES)

### CHANGED: CM-AKF clamp range (matches thesis para 143 and rule_akf_1D.py)
R_MIN = 1.0
R_MAX = 10000.0

# ---------- 1. Load & concatenate synthetic data ----------
def load_all_scenarios(data_dir: Path) -> pd.DataFrame:
    files = sorted(glob.glob(str(data_dir / "synth_E*_data.csv")))
    if not files:
        raise FileNotFoundError(f"No synth_E*_data.csv found in {data_dir}")
    dfs = []
    for f in files:
        df = pd.read_csv(f)
        print(f"  Loaded {Path(f).name}: {len(df)} rows")
        dfs.append(df)
    return pd.concat(dfs, ignore_index=True)

# ---------- 2. Feature extraction ----------
def extract_features(df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract 3-feature matrix and log1p(R_label) target.
    R_label is clamped to [R_MIN, R_MAX] before log transform to match
    CM-AKF definition; this prevents extreme outliers from destabilizing
    training and INT8 quantization.
    """
    f1 = df["tof_residual"].values
    f2 = df["tof_residual_var"].values
    f3 = df["tof_residual_mean"].values
    y_raw = df["R_label"].values

    X = np.column_stack([f1, f2, f3]).astype(np.float32)
    y_raw = y_raw.astype(np.float32)

    mask = ~(np.isnan(X).any(axis=1) | np.isnan(y_raw))
    X = X[mask]
    y_raw = y_raw[mask]

    ### CHANGED: clamp then log-transform
    y_clamped = np.clip(y_raw, R_MIN, R_MAX)
    y_log = np.log1p(y_clamped).astype(np.float32)   # log(1+R)

    print(f"  Raw R range:     [{y_raw.min():.2f}, {y_raw.max():.2f}]")
    print(f"  Clamped R range: [{y_clamped.min():.2f}, {y_clamped.max():.2f}]")
    print(f"  log1p(R) range:  [{y_log.min():.4f}, {y_log.max():.4f}]")

    return X, y_log, y_clamped   ### CHANGED: also return clamped raw for eval

# ---------- 3. Normalization ----------
class MinMaxScaler:
    def fit(self, X):
        self.min_ = X.min(axis=0)
        self.max_ = X.max(axis=0)
        self.range_ = self.max_ - self.min_
        self.range_[self.range_ == 0] = 1.0
        return self
    def transform(self, X):
        return (X - self.min_) / self.range_
    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)
    def print_mcu_constants(self):
        print("// === Normalization constants for MCU firmware ===")
        for i, name in enumerate(FEATURE_NAMES):
            print(f"#define {name.upper()}_MIN   {self.min_[i]:.6f}f")
            print(f"#define {name.upper()}_RANGE {self.range_[i]:.6f}f")

# ---------- 4. FCN model ----------
def build_model(n_features: int) -> keras.Model:
    """
    Architecture: 3 -> 16 (ReLU) -> 8 (ReLU) -> 1 (linear, log-space output)
    The MCU will apply expm1() on the output to recover R in mm^2.
    """
    inputs = keras.Input(shape=(n_features,), name="features")
    x = layers.Dense(16, activation="relu", name="hidden1")(inputs)
    x = layers.Dense(8,  activation="relu", name="hidden2")(x)
    ### CHANGED: softplus -> linear (working in log-space)
    outputs = layers.Dense(1, activation="linear", name="log_R_estimate")(x)
    return keras.Model(inputs, outputs, name="tinyml_akf_3feat")

# ---------- 5. INT8 quantization ----------
def quantize_to_int8(keras_model: keras.Model, X_train: np.ndarray, out_path: str):
    def representative_dataset():
        idx = np.random.choice(len(X_train), size=min(100, len(X_train)), replace=False)
        for i in idx:
            yield [X_train[i:i+1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    with open(out_path, "wb") as f:
        f.write(tflite_model)
    print(f"  INT8 TFLite model saved: {out_path} ({len(tflite_model)/1024:.2f} KB)")
    return tflite_model

# ---------- 6. Float vs INT8 comparison ----------
def compare_float_vs_int8(float_model, tflite_bytes, X_test, y_test_raw):
    """
    Compare in original R space (not log space) so the ±10% criterion
    reflects true R estimation accuracy for MCU deployment.
    """
    ### CHANGED: both predictions are in log-space, then expm1 to R
    y_pred_log_float = float_model.predict(X_test, verbose=0).flatten()
    y_pred_float = np.expm1(y_pred_log_float)

    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()
    input_details  = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    in_scale,  in_zero  = input_details["quantization"]
    out_scale, out_zero = output_details["quantization"]

    y_pred_int8 = []
    for x in X_test:
        # Quantize input
        x_q = np.round(x / in_scale + in_zero).astype(np.int8)
        interpreter.set_tensor(input_details["index"], x_q.reshape(1, -1))
        interpreter.invoke()
        # Dequantize output — cast to int32 first to avoid int8 overflow
        y_q = interpreter.get_tensor(output_details["index"])[0, 0]
        y_log = (np.int32(y_q) - np.int32(out_zero)) * out_scale  ### FIX: int8 overflow
        y_pred_int8.append(np.expm1(y_log))
    y_pred_int8 = np.array(y_pred_int8)

    # Clamp predictions to CM-AKF range to match MCU runtime behavior
    y_pred_float = np.clip(y_pred_float, R_MIN, R_MAX)
    y_pred_int8  = np.clip(y_pred_int8,  R_MIN, R_MAX)

    eps = 1e-6
    rel_err = np.abs(y_pred_int8 - y_pred_float) / (np.abs(y_pred_float) + eps)
    max_rel = rel_err.max() * 100
    mean_rel = rel_err.mean() * 100

    # Also evaluate against true clamped labels
    mae_float = np.abs(y_pred_float - y_test_raw).mean()
    mae_int8  = np.abs(y_pred_int8  - y_test_raw).mean()

    print(f"  Float32 R: mean={y_pred_float.mean():.2f}, std={y_pred_float.std():.2f}")
    print(f"  INT8    R: mean={y_pred_int8.mean():.2f}, std={y_pred_int8.std():.2f}")
    print(f"  True    R: mean={y_test_raw.mean():.2f}, std={y_test_raw.std():.2f}")
    print(f"  MAE vs true R:  float32={mae_float:.2f}, int8={mae_int8:.2f}")
    print(f"  Float->INT8 relative error: mean={mean_rel:.2f}%, max={max_rel:.2f}%")
    if max_rel < 10.0:
        print(f"  PASS: max float->int8 relative error < 10%")
    else:
        print(f"  WARNING: max float->int8 relative error exceeds 10%")

    return y_pred_float, y_pred_int8

# ---------- Main ----------
def main():
    print("=" * 60)
    print("TinyML AKF Training Pipeline (3-feature, rev2 log-space)")
    print("=" * 60)

    print("\n[1] Loading synthetic data...")
    df = load_all_scenarios(DATA_DIR)
    print(f"  Total rows (pre-filter): {len(df)}")

    print("\n[2] Extracting 3-feature matrix + log-transforming labels...")
    X, y_log, y_raw_clamped = extract_features(df)
    print(f"  Samples after NaN removal: {len(X)}")

    print("\n[3] Splitting data (80/10/10 shuffled)...")
    n = len(X)
    idx = np.random.permutation(n)
    n_train = int(0.8 * n)
    n_val   = int(0.1 * n)
    tr = idx[:n_train]
    vl = idx[n_train:n_train + n_val]
    te = idx[n_train + n_val:]
    X_train, y_train_log = X[tr], y_log[tr]
    X_val,   y_val_log   = X[vl], y_log[vl]
    X_test,  y_test_log  = X[te], y_log[te]
    y_test_raw = y_raw_clamped[te]
    print(f"  Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

    print("\n[4] Fitting normalization on training set...")
    scaler = MinMaxScaler().fit(X_train)
    X_train_n = scaler.transform(X_train)
    X_val_n   = scaler.transform(X_val)
    X_test_n  = scaler.transform(X_test)
    scaler.print_mcu_constants()

    print("\n[5] Building FCN model...")
    model = build_model(N_FEATURES)
    model.summary()
    print(f"  Total parameters: {model.count_params()}")

    print("\n[6] Training...")
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=3e-3),   ### CHANGED: 1e-3 -> 3e-3
        loss="mse",
        metrics=["mae"],
    )
    early_stop = keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=20, restore_best_weights=True, verbose=1,
    )
    history = model.fit(
        X_train_n, y_train_log,
        validation_data=(X_val_n, y_val_log),
        epochs=300,
        batch_size=64,
        callbacks=[early_stop],
        verbose=2,
    )

    print("\n[7] Test set evaluation (log-space)...")
    test_loss, test_mae = model.evaluate(X_test_n, y_test_log, verbose=0)
    print(f"  Test MSE (log-space):  {test_loss:.4f}")
    print(f"  Test MAE (log-space):  {test_mae:.4f}")

    model.save("tinyml_akf_3feat.keras")
    print("  Float model saved: tinyml_akf_3feat.keras")

    print("\n[8] INT8 quantization...")
    tflite_bytes = quantize_to_int8(model, X_train_n, "tinyml_akf_3feat_int8.tflite")

    print("\n[9] Float32 vs INT8 comparison (R-space, post expm1)...")
    compare_float_vs_int8(model, tflite_bytes, X_test_n, y_test_raw)

    print("\n" + "=" * 60)
    print("Pipeline complete.")
    print("=" * 60)

if __name__ == "__main__":
    main()